import { expect, test } from "vitest";
import { gradeMarket } from "@/lib/market-grading";
const s = (h:number,a:number,hh=0,ha=0,fin=true)=>({started:true,live:!fin,finished:fin,postponed:false,ft:{h,a},ht:{h:hh,a:ha},htDone:true,home:"Arsenal",away:"Chelsea"});
const cases: [string, ReturnType<typeof s>, string|null][] = [
 ["Both Teams To Score - Yes", s(1,1), "won"],
 ["Both Teams To Score - No", s(1,1), "lost"],
 ["Both Teams To Score - No", s(2,0), "won"],
 ["Both Teams To Score - Yes", s(1,0,0,0,false), null],
 ["GG", s(1,2), "won"],
 ["NG", s(1,0), "won"],
 ["Goal|Goal-Goal", s(1,1), "won"],
 ["Goal|NoGoal", s(1,1), "lost"],
 ["1", s(2,1), "won"],
 ["X", s(1,1), "won"],
 ["Over 2.5", s(2,1), "won"],
 ["Under 2.5", s(2,1), "lost"],
 ["Total Goals 2.5 · Over 2.5", s(1,1), "lost"],
 ["Over 2", s(1,1), "void"],
 ["Double chance · 1X", s(1,1), "won"],
 ["1X2|1", s(0,1), "lost"],
 ["U/O|O2.5", s(3,1), "won"],
 ["Correct score|2:1", s(2,1), "won"],
 ["Handicap · 1 (-1)", s(2,0), "won"],
 ["Draw No Bet - Arsenal", s(1,1), "void"],
 ["1 & Over 2.5", s(3,0), "won"],
 ["1X & GG", s(1,1), "won"],
 ["Half Time Result - 1", s(2,1,1,0), "won"],
 ["Odd/Even - Odd", s(2,1), "won"],
 ["Clean sheet - Home Yes", s(2,0), "won"],
 ["HT/FT - 1/1", s(2,1,1,0), "won"],
 ["Multigoals 2-3", s(2,1), "won"],
 ["Arsenal to score", s(1,0), "won"],
 ["Highest scoring half - 2nd half", s(3,0,1,0), "won"],
];
test.each(cases)("%s", (pick, snap, want) => { expect(gradeMarket(pick, snap as any)).toBe(want); });
